default: &default
  adapter: postgresql
  encoding: unicode
  database: agenda_template
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: agenda_template_development

test:
  <<: *default
  database: agenda_template_test

production:
  <<: *default
  database: agenda_template_production

